# Generated by Django 5.2.10 on 2026-01-25 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0002_room_and_post_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='current_phase',
            field=models.CharField(choices=[('understand', 'Understand'), ('propose', 'Propose'), ('critique', 'Critique'), ('decide', 'Decide')], default='understand', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='message_board.activity'),
        ),
    ]
