# Generated by Django 5.2.10 on 2026-01-25 19:59

from django.db import migrations


def seed_agents(apps, schema_editor):
    Agent = apps.get_model('message_board', 'Agent')
    
    # Create Facilitator Agent
    Agent.objects.get_or_create(
        name='Facilitator Agent',
        defaults={
            'description': 'Keeps the group on task, prompts quieter members, and summarizes decisions.',
            'is_active': True
        }
    )
    
    # Create Socratic Agent
    Agent.objects.get_or_create(
        name='Socratic Agent',
        defaults={
            'description': 'Asks clarification questions when reasoning is incomplete or unsupported.',
            'is_active': True
        }
    )


def remove_agents(apps, schema_editor):
    Agent = apps.get_model('message_board', 'Agent')
    Agent.objects.filter(name__in=['Facilitator Agent', 'Socratic Agent']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0004_agent_intervention'),
    ]

    operations = [
        migrations.RunPython(seed_agents, remove_agents),
    ]
