# Generated by Django 6.0.1 on 2026-01-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0006_room_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('problem-solving', 'Problem-Solving'), ('discussion', 'Discussion'), ('design critique', 'Design Critique')], default='discussion', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='phases',
            field=models.JSONField(default=list),
        ),
    ]
