# Generated by Django 6.0.1 on 2026-01-27 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0008_alter_activity_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phase_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='activity_is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='activity_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='selected_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='message_board.activity'),
        ),
    ]
