# Generated by Django 6.0.1 on 2026-01-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0009_post_phase_index_room_activity_is_running_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='phase_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
