# Generated by Django 6.0.1 on 2026-01-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0010_intervention_phase_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lacks_evidence',
            field=models.BooleanField(default=False),
        ),
    ]
