# Generated by Django 6.0.1 on 2026-01-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0013_evidencenudgestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='activity_run_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='activity_run_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='activity_run_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
