# Generated by Django 6.0.1 on 2026-02-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0014_intervention_activity_run_id_post_activity_run_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_run_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_started_at', models.DateTimeField(blank=True, null=True)),
                ('activity_ended_at', models.DateTimeField(blank=True, null=True)),
                ('participation_data', models.JSONField(default=dict)),
                ('process_data', models.JSONField(default=dict)),
                ('quality_data', models.JSONField(default=dict)),
                ('extracted_content', models.JSONField(default=dict)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='message_board.activity')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='message_board.room')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('room', 'activity_run_id')},
            },
        ),
    ]
