# Generated by Django 6.0.1 on 2026-02-09 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0016_intervention_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='last_seen_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
