# Generated by Django 6.0.1 on 2026-02-09 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0017_roommember_last_seen_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommember',
            name='last_seen_at',
        ),
    ]
