# Generated by Django 6.0.1 on 2026-03-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0022_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='agent_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
