# Generated by Django 6.0.1 on 2026-03-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_board", "0023_activity_agent_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="active_agents",
            field=models.ManyToManyField(
                blank=True, related_name="activities", to="message_board.agent"
            ),
        ),
    ]
