# Generated by Django 6.0.1 on 2026-03-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0024_activity_active_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('learner', 'Learner'), ('facilitator', 'Facilitator')], default='learner', max_length=20),
        ),
    ]
