# Generated by Django 6.0.1 on 2026-03-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0025_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='activity_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='phase_override_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
